---
# tasks file for roles/backups_consul
- name: install restic
  apt:
    name: restic
    state: present
    update_cache: yes
    cache_valid_time: 3600
  
- name: install restic
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { dir: "/root/.config/restic/", mode: "0750" }
    - { dir: "/opt/scripts/backups", mode: "0750" }
    - { dir: "/var/log/backups/", mode: "0755" }
    - { dir: "/var/lib/cron/", mode: "0755" }

- name: add restic configuration file
  copy:
    content: |
      export AWS_DEFAULT_REGION="us-east-1"
      export RESTIC_REPOSITORY="s3:http://{{ minio_endpoint }}:9000/backups-consul"
      export AWS_ACCESS_KEY_ID="{{ backups_consul_key }}"
      export AWS_SECRET_ACCESS_KEY="{{ backups_consul_secret_key }}"
      export AWS_S3_FORCE_PATH_STYLE="true" 
      export RESTIC_PASSWORD="{{ backups_consul_secret_password }}"
    dest: /root/.config/restic/restic_consul.creds
    owner: root
    group: root
    mode: 0700

- name: install the consul backup script
  template:
    src: backup_consul.sh.j2
    dest: /opt/scripts/backups/backup_consul.sh
    owner: root
    group: root
    mode: 0750

- name: add a cron for backups
  template:
    src: backup_consul.j2
    dest: /etc/cron.d/backup_consul
    owner: root
    group: root
    mode: 0750

#----------
# ansible/roles/consul/backups_consul/tasks/main.yml
# ... (après la tâche "add a cron for backups")

- name: Ensure cron service is running
  service:
    name: cron
    state: started
    enabled: yes

- name: Verify cron job is installed
  shell: crontab -l | grep backup_consul || cat /etc/cron.d/backup_consul
  register: cron_check
  failed_when: false
  changed_when: false

- name: Show cron configuration
  debug:
    var: cron_check.stdout_lines

#------------------------

- name: check if restic already init
  shell: |
    source /root/.config/restic/restic_consul.creds
    restic snapshots
  args:
    executable: /bin/bash
  register: __restic_init
  ignore_errors: true
  
- name: init restic if needed
  shell: |
    source /root/.config/restic/restic_consul.creds
    restic init
  args:
    executable: /bin/bash
  when: __restic_init.rc != 0