kubernetes_tooling_helm_version: 3.16.1
kubernetes_openstack_username: ""
kubernetes_openstack_password: ""
kubernetes_openstack_domain_name: "default"
kubernetes_openstack_auth_url: "https://api.pub1.infomaniak.cloud/identity"
kubernetes_openstack_tenant_id: ""
kubernetes_openstack_region: ""
kubernetes_helm_consulsync_version: "0.45.0"
kubernetes_helm_cinder_version: "2.30.0"
kubernetes_helm_prometheus_stack_version: "62.3.1"
kubernetes_helm_prometheus_stack_retention: "4h"
kubernetes_helm_prometheus_stack_sc: "csi-cinder-sc-delete"
kubernetes_helm_prometheus_stack_storage_size: "20Gi"
kubernetes_helm_prometheus_prom_replicas: 2
#kubernetes_helm_prometheus_prom_remote_write: "http://vmetrics.service.staner.consul:8428/api/v1/write"
kubernetes_helm_prometheus_prom_remote_write: "http://vminsert-victoriametrics.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"

kubernetes_helm_prometheus_grafana_datasource: "http://vmselect-victoriametrics.monitoring.svc.cluster.local:8481/select/0/prometheus"
kubernetes_helm_prometheus_stack_grafana_sc: "csi-cinder-sc-delete"

kubernetes_helm_vmcluster_name: "victoriametrics"
kubernetes_helm_vmoperator_stack_version: "0.34.8"
kubernetes_helm_vmcluster_namespace: "monitoring"
kubernetes_helm_vmcluster_vmselect_replicas: "2"
kubernetes_helm_vmcluster_vminsert_replicas: "2"
kubernetes_helm_vmcluster_vmstorage_replicas: "2"
kubernetes_helm_vmcluster_vmstorage_retention: "1y"
kubernetes_helm_vmcluster_vmselect_size: "2Gi"
kubernetes_helm_vmcluster_vmstorage_size: "20Gi"
kubernetes_helm_vmcluster_vmstorage_storageclass: "csi-cinder-sc-delete"
kubernetes_helm_vmcluster_vmselect_storageclass: "csi-cinder-sc-delete"

kubernetes_helm_consul_exporter_version: "1.0.0"
kubernetes_helm_consul_exporter_server: "consul.service.consul:8500"

kubernetes_helm_vmcluster_vlogs_retention: "1y"
kubernetes_helm_vmcluster_vlogs_size: "30Gi"
kubernetes_helm_vmcluster_vlogs_storageclass: "csi-cinder-sc-delete"
kubernetes_helm_prometheus_grafana_datasource_logs: "http://vlogs-vlogs.service.consul:9428"
kubernetes_helm_prometheus_stack_grafana_ds_vlogs_version: "0.5.0"