---
# Fixed MQTT role tasks - removed missing templates
# File: /ansible/roles/mqtt/tasks/main.yml

- name: Install Mosquitto with dashboard support
  apt:
    name:
      - mosquitto
      - mosquitto-clients
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Stop Mosquitto temporarily for configuration
  systemd:
    name: mosquitto
    state: stopped
  failed_when: false

- name: Create mosquitto system user
  user:
    name: mosquitto
    system: yes
    shell: /usr/sbin/nologin
    home: /var/lib/mosquitto
    createhome: yes

- name: Create enhanced Mosquitto directories
  file:
    path: "{{ item }}"
    state: directory
    owner: mosquitto
    group: mosquitto
    mode: '0755'
  loop:
    - "{{ mqtt_data_dir }}"
    - "{{ mqtt_data_dir }}/data"
    - "{{ mqtt_data_dir }}/log"
    - /etc/mosquitto/conf.d

- name: Configure enhanced Mosquitto
  template:
    src: mosquitto.conf.j2
    dest: /etc/mosquitto/mosquitto.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart mosquitto

- name: Create enhanced MQTT users with dashboard access
  shell: |
    rm -f /etc/mosquitto/passwd
    touch /etc/mosquitto/passwd
    # Core IoT users
    mosquitto_passwd -b /etc/mosquitto/passwd iot iot123
    mosquitto_passwd -b /etc/mosquitto/passwd telegraf telegraf123
    mosquitto_passwd -b /etc/mosquitto/passwd admin admin123
    # Energy system users
    mosquitto_passwd -b /etc/mosquitto/passwd energy_monitor energy123
    # Dashboard user for web interface
    mosquitto_passwd -b /etc/mosquitto/passwd dashboard dash123
  args:
    creates: /etc/mosquitto/passwd

- name: Set secure password file permissions
  file:
    path: /etc/mosquitto/passwd
    owner: mosquitto
    group: mosquitto
    mode: '0600'

- name: Deploy enhanced ACL configuration
  template:
    src: acl.j2
    dest: /etc/mosquitto/acl
    owner: mosquitto
    group: mosquitto
    mode: '0644'
    backup: yes

- name: Enable and start enhanced Mosquitto
  systemd:
    name: mosquitto
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for MQTT to be ready
  wait_for:
    port: 1883
    delay: 5
    timeout: 30

- name: Wait for WebSocket port
  wait_for:
    port: 9001
    delay: 2
    timeout: 30

- name: Test enhanced MQTT connectivity
  shell: |
    # Test basic MQTT connectivity
    timeout 5 mosquitto_pub -h localhost -p 1883 -u iot -P iot123 -t test/connection -m "Enhanced MQTT OK" || echo "MQTT test failed"
    
    # Test dashboard user access
    timeout 5 mosquitto_pub -h localhost -p 1883 -u dashboard -P dash123 -t dashboard/heartbeat -m "Dashboard user OK" || echo "Dashboard user test failed"
    
    # Test energy topics with retained messages
    timeout 5 mosquitto_pub -h localhost -p 1883 -u iot -P iot123 -t energy/datacenter/status -r -m '{"status":"ready","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' || echo "Energy topic test failed"
    
    echo "Enhanced MQTT broker ready for dashboard"
  register: mqtt_enhanced_test
  failed_when: false

- name: Display enhanced MQTT configuration summary
  debug:
    msg: |
      ✅ Enhanced MQTT Broker for Energy Dashboard:
      
      🔌 Network:
      - MQTT Port: 1883
      - WebSocket Port: 9001
      
      👥 Users:
      - iot: IoT devices and sensors (read/write)
      - telegraf: InfluxDB collector (read)
      - admin: Full system access
      - energy_monitor: Energy system management
      - dashboard: Web dashboard (read-only)
      
      📊 Dashboard Topics:
      - energy/datacenter/dashboard (main aggregated data)
      - energy/solar/datacenter/* (solar production)
      - energy/battery/datacenter/* (battery status)
      - energy/consumption/datacenter/* (power usage)
      - weather/datacenter/current (weather data)
      
      Test Results: {{ mqtt_enhanced_test.stdout_lines[-1] if mqtt_enhanced_test.stdout_lines else 'Configuration completed' }}
# ---
# - name: Install Mosquitto
#   apt:
#     name:
#       - mosquitto
#       - mosquitto-clients
#     state: present
#     update_cache: yes
#     cache_valid_time: 3600

# - name: Stop Mosquitto temporarily
#   systemd:
#     name: mosquitto
#     state: stopped
#   failed_when: false

# - name: Create mosquitto user
#   user:
#     name: mosquitto
#     system: yes
#     shell: /usr/sbin/nologin
#     home: /var/lib/mosquitto
#     createhome: yes

# - name: Create Mosquitto directories
#   file:
#     path: "{{ item }}"
#     state: directory
#     owner: mosquitto
#     group: mosquitto
#     mode: '0755'
#   loop:
#     - "{{ mqtt_data_dir }}"
#     - "{{ mqtt_data_dir }}/data"
#     - "{{ mqtt_data_dir }}/log"
#     - /etc/mosquitto/conf.d

# - name: Configure Mosquitto
#   template:
#     src: mosquitto.conf.j2
#     dest: /etc/mosquitto/mosquitto.conf
#     owner: root
#     group: root
#     mode: '0644'
#   notify: restart mosquitto

# - name: Create MQTT users with energy access
#   shell: |
#     rm -f /etc/mosquitto/passwd
#     touch /etc/mosquitto/passwd
#     # Existing users
#     mosquitto_passwd -b /etc/mosquitto/passwd iot iot123
#     mosquitto_passwd -b /etc/mosquitto/passwd telegraf telegraf123
#     mosquitto_passwd -b /etc/mosquitto/passwd admin admin123
#     # New energy-specific users (optional)
#     mosquitto_passwd -b /etc/mosquitto/passwd energy_monitor energy123
#     mosquitto_passwd -b /etc/mosquitto/passwd solar_system solar123
#   args:
#     creates: /etc/mosquitto/passwd

# - name: Set password file permissions
#   file:
#     path: /etc/mosquitto/passwd
#     owner: mosquitto
#     group: mosquitto
#     mode: '0600'

# - name: Create extended ACL file
#   template:
#     src: acl.j2
#     dest: /etc/mosquitto/acl
#     owner: mosquitto
#     group: mosquitto
#     mode: '0644'

# - name: Enable and start Mosquitto
#   systemd:
#     name: mosquitto
#     enabled: yes
#     state: started
#     daemon_reload: yes

# - name: Wait for MQTT to be ready
#   wait_for:
#     port: 1883
#     delay: 5

# - name: Test MQTT connectivity with energy topics
#   shell: |
#     # Test basic connectivity
#     timeout 5 mosquitto_pub -h localhost -p 1883 -u iot -P iot123 -t test/connection -m "MQTT OK" || true
    
#     # Test energy topics
#     timeout 5 mosquitto_pub -h localhost -p 1883 -u iot -P iot123 -t energy/test -m "Energy MQTT OK" || true
    
#     echo "MQTT broker ready for IoT and Energy data"
#   register: mqtt_test
#   failed_when: false

# - name: Display MQTT test results
#   debug:
#     msg: |
#       ✅ MQTT Broker Configuration:
#       - Port 1883: Standard MQTT
#       - Port 9001: WebSockets
#       - Users: iot, telegraf, admin, energy_monitor, solar_system
#       - Topics: sensors/*, devices/*, energy/*, weather/*
#       Test result: {{ mqtt_test.stdout_lines[-1] if mqtt_test.stdout_lines else 'Test completed' }}

