{
 "title": "Consul",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Leaders Nb",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "consul_raft_leader" }
   ]
  },
  {
   "title": "Peers Nb",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "consul_raft_peers" }
   ]
  },
  {
   "title": "Passing Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{status=\"passing\"}) by(status)",
     "legendFormat": "Passing"
    }
   ]
  },
  {
   "title": "Critical Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check!=\"_node_maintenance\",status=\"critical\"}) by(status)",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Warning Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{status=\"warning\"}) by(status)",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Maint Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"_node_maintenance\",status=\"critical\"}) by(status)",
     "legendFormat": "Maintenance"
    }
   ]
  },
  {
   "title": "Maint Nodes",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"_node_maintenance\"}==1) by(node)",
     "legendFormat": "Maintenance"
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Passing Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_service_status{status=\"passing\"}) by(status)",
     "legendFormat": "Passing"
    }
   ]
  },
  {
   "title": "Critical Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum( ((sum(consul_health_service_status{check!~\"_service_maintenance.*\",status!=\"passing\"}) by (service_name,node,dc) - \n (sum(consul_service_checks) by (service_name,node,dc) - sum(consul_health_service_status{check!~\"_service_maintenance.*\"}) by (service_name,node,dc)))\n- on(node) group_left sum(\nsum(consul_health_node_status) by(node) - sum(consul_health_node_status{check!~\"_node_maintenance\"}) by(node)\n )  by(node))) by (service_name) / sum(consul_health_service_status{check!~\"_service_maintenance.*\"}) >0",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Warning Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_service_status{status=\"warning\"}) by(status)",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Maint Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_service_status{check=~\"_service_maintenance.*\"})",
     "legendFormat": "Maintenance"
    }
   ]
  },
  {
   "title": "Passing Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instances per service",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(sum(consul_health_service_status{status=\"passing\"}) by (service_name) - sum(consul_health_service_status{status=\"maintenance\"}) by (service_name)) / sum(consul_health_service_status) by (service_name)*100"
    },
    {
     "expr": "sum(consul_health_service_status{status=\"passing\"}) by (service_name)"
    }
   ]
  }
 ]
}