---
# tasks file for roles/dns-common
- name: Install utils
  apt:
    name: dnsmasq
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: stop systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true
  ignore_errors: true

- name: edit resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root

- name: add hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"
    state: present

- name: add dnsmasq config
  template:
    src: 10-consul.conf.j2
    dest: /etc/dnsmasq.d/10-consul.conf         
    mode: 0755
  notify: restart_dnsmasq

- name: dnsmasq started
  systemd:
    name: dnsmasq
    state: started
    enabled: true
