---
- name: Configure MinIO
  hosts: meta-app_minio
  gather_facts: true
  become: true
  vars:
    minio_data_dir: "/data"
    minio_access_key: "{{ backups_s3_secret_key }}"
    minio_secret_key: "{{ vault_backups_consul_secret_key }}"
    volumes_disks:
      - { disk: '/dev/vdb', path: '{{ minio_data_dir }}', owner: "minio" }
  roles:
    - volumes
    - minio
    - consul/consul  # Ajouter l'agent Consul
    - consul/consul_service_minio
    - monitoring/custom_metrics

