data_dir: "/var/lib/vector"

sources:
  journald:
    type: journald

sinks:
  loki_journald:
    type: loki
    labels:
      instance: "{{ ansible_hostname }}"
      type: "journald"
    inputs:
      - journald
    endpoint: http://{{ vector_loki_endpoint }}

{% if vector_loki_path != "" %}
    path: {{ vector_loki_path }}
    compression: gzip
{% endif %}

    encoding:
      codec: "json"
    healthcheck:
      enabled: false
