---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Add InfluxDB GPG key
  shell: |
    curl -s https://repos.influxdata.com/influxdata-archive_compat.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null
  args:
    creates: /etc/apt/trusted.gpg.d/influxdb.gpg

- name: Add InfluxDB repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/debian stable main"
    state: present
    filename: influxdb

- name: Install InfluxDB 2
  apt:
    name:
      - influxdb2
      - influxdb2-cli
    state: present
    update_cache: yes

- name: Ensure influxdb user exists (only if not active)
  command: id influxdb
  register: influxdb_user_check
  ignore_errors: true

- name: Create InfluxDB user if not exists
  user:
    name: influxdb
    system: yes
    shell: /bin/false
    home: /var/lib/influxdb
    createhome: yes
  when: influxdb_user_check.rc != 0


- name: Create InfluxDB directories
  file:
    path: "{{ item }}"
    state: directory
    owner: influxdb
    group: influxdb
    mode: '0755'
  loop:
    - "{{ influxdb_data_dir }}/influxdb"
    - /etc/influxdb2

- name: Configure InfluxDB
  template:
    src: config.yml.j2
    dest: /etc/influxdb2/config.yml
    owner: influxdb
    group: influxdb
    mode: '0644'
  notify: restart influxdb

- name: Start InfluxDB service
  systemd:
    name: influxdb
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for InfluxDB to be ready
  wait_for:
    port: 8086
    delay: 5
    timeout: 60
